version: '3.6'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/src
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
    command: npm run serve